test_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: sakila_database
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
    local:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: postgres
      schema: public
      threads: 1
elementary:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: postgres
      schema: public_elementary
      threads: 1